version: '2.4'

# Ashchan mTLS ServiceMesh Network Configuration
# All services communicate via mutual TLS on the ashchan-mesh network
# DNS-based service discovery: <service>.ashchan.local

networks:
  ashchan-mesh:
    driver: bridge
  ashchan-public:
    driver: bridge

services:
  # ─────────────────────────────────────────────────────────────
  # Infrastructure Services
  # ─────────────────────────────────────────────────────────────

  postgres:
    image: docker.io/postgres:16-alpine
    container_name: ashchan-postgres-1
    hostname: postgres.ashchan.local
    user: "70:70"  # postgres user in official image
    environment:
      POSTGRES_USER: ashchan
      POSTGRES_PASSWORD: ashchan
      POSTGRES_DB: ashchan
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations:/app/db/migrations:ro
    networks:
      - ashchan-mesh
    healthcheck:
      test: "pg_isready -U ashchan"
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: docker.io/redis:7-alpine
    container_name: ashchan-redis-1
    hostname: redis.ashchan.local
    user: "999:999"  # redis user in official image
    command: redis-server --requirepass "${REDIS_PASSWORD:-changeme}"
    volumes:
      - redis_data:/data
    networks:
      - ashchan-mesh
    healthcheck:
      test: "redis-cli -a \"${REDIS_PASSWORD:-changeme}\" ping"
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  minio:
    image: docker.io/minio/minio:latest
    container_name: ashchan-minio-1
    hostname: minio.ashchan.local
    user: "1000:1000"  # minio user in official image
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ashchan
      MINIO_ROOT_PASSWORD: ashchan123
    volumes:
      - minio_data:/data
    networks:
      - ashchan-mesh
    healthcheck:
      test: "curl -f http://localhost:9000/minio/health/live"
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  # ─────────────────────────────────────────────────────────────
  # Application Services (mTLS enabled)
  # ─────────────────────────────────────────────────────────────

  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    container_name: ashchan-gateway-1
    hostname: gateway.ashchan.local
    ports:
      - "9501:9501"   # Public HTTP
      - "9443:9443"   # Public HTTPS (optional)
      - "8443:8443"   # Internal mTLS
    env_file:
      - ./services/api-gateway/.env
    volumes:
      - ./frontend/static:/app/frontend/static:ro
      - ./certs/services/gateway:/etc/mtls/gateway:ro
      - ./certs/ca:/etc/mtls/ca:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ashchan-public
      - ashchan-mesh
    healthcheck:
      test: "curl -f http://localhost:9501/health || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  auth-accounts:
    build:
      context: ./services/auth-accounts
      dockerfile: Dockerfile
    container_name: ashchan-auth-1
    hostname: auth.ashchan.local
    ports:
      - "8502:8443"   # Internal mTLS
    env_file:
      - ./services/auth-accounts/.env
    volumes:
      - ./certs/services/auth:/etc/mtls/auth:ro
      - ./certs/ca:/etc/mtls/ca:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ashchan-mesh
    healthcheck:
      test: "curl -f http://localhost:9502/health || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  boards-threads-posts:
    build:
      context: ./services/boards-threads-posts
      dockerfile: Dockerfile
    container_name: ashchan-boards-1
    hostname: boards.ashchan.local
    ports:
      - "8503:8443"   # Internal mTLS
    env_file:
      - ./services/boards-threads-posts/.env
    volumes:
      - ./certs/services/boards:/etc/mtls/boards:ro
      - ./certs/ca:/etc/mtls/ca:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ashchan-mesh
    healthcheck:
      test: "curl -f http://localhost:9503/health || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  media-uploads:
    build:
      context: ./services/media-uploads
      dockerfile: Dockerfile
    container_name: ashchan-media-1
    hostname: media.ashchan.local
    ports:
      - "8504:8443"   # Internal mTLS
    env_file:
      - ./services/media-uploads/.env
    volumes:
      - ./certs/services/media:/etc/mtls/media:ro
      - ./certs/ca:/etc/mtls/ca:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - ashchan-mesh
    healthcheck:
      test: "curl -f http://localhost:9504/health || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  search-indexing:
    build:
      context: ./services/search-indexing
      dockerfile: Dockerfile
    container_name: ashchan-search-1
    hostname: search.ashchan.local
    ports:
      - "8505:8443"   # Internal mTLS
    env_file:
      - ./services/search-indexing/.env
    volumes:
      - ./certs/services/search:/etc/mtls/search:ro
      - ./certs/ca:/etc/mtls/ca:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ashchan-mesh
    healthcheck:
      test: "curl -f http://localhost:9505/health || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  moderation-anti-spam:
    build:
      context: ./services/moderation-anti-spam
      dockerfile: Dockerfile
    container_name: ashchan-moderation-1
    hostname: moderation.ashchan.local
    ports:
      - "8506:8443"   # Internal mTLS
    env_file:
      - ./services/moderation-anti-spam/.env
    volumes:
      - ./certs/services/moderation:/etc/mtls/moderation:ro
      - ./certs/ca:/etc/mtls/ca:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ashchan-mesh
    healthcheck:
      test: "curl -f http://localhost:9506/health || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  minio_data:
