#!/usr/bin/env bash
#
# Update Ashchan services to fetch secrets from OpenBao
#
# This script modifies systemd service files to use OpenBao
# for secret retrieval at startup.
#
# Usage: sudo tools/openbao/update-services.sh
#
# License: Apache 2.0
#

set -euo pipefail

readonly ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
readonly SERVICES_DIR="$ROOT_DIR/services"
readonly ASHCHAN_OPENBAO_DIR="/etc/ashchan/openbao"
readonly OPENBAO_ADDR="http://localhost:8200"

readonly SERVICES=(
    "api-gateway:gateway:9501"
    "auth-accounts:auth:9502"
    "boards-threads-posts:boards:9503"
    "media-uploads:media:9504"
    "search-indexing:search:9505"
    "moderation-anti-spam:moderation:9506"
)

readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[✓]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

print_header() {
    echo ""
    echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
    echo -e "${BLUE}  $1${NC}"
    echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
    echo ""
}

# Create secret fetch script for a service
create_fetch_script() {
    local service_name="$1"
    local service_short="$2"

    local fetch_script="/usr/local/bin/ashchan-${service_short}-fetch-secrets"

    cat > "$fetch_script" << EOF
#!/usr/bin/env bash
#
# Fetch secrets from OpenBao for ${service_name}
# Generated by update-services.sh
#

set -euo pipefail

OPENBAO_ADDR="${OPENBAO_ADDR}"
OPENBAO_ROLE="${service_short}-service"
SECRET_PATH="secret/ashchan/services/${service_short}"
GLOBAL_SECRET_PATH="secret/ashchan/global"

# Read client certificate paths
CLIENT_CERT="/etc/ashchan/openbao/client/client.crt"
CLIENT_KEY="/etc/ashchan/openbao/client/client.key"
CA_CERT="/etc/ashchan/openbao/ca.crt"

# Get token from Kubernetes service account or file
if [[ -f "/var/run/secrets/kubernetes.io/serviceaccount/token" ]]; then
    # Kubernetes mode
    JWT_TOKEN=\$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
    RESPONSE=\$(curl -sf -X POST "\${OPENBAO_ADDR}/v1/auth/kubernetes/login" \\
        -d "{\"role\": \"\${OPENBAO_ROLE}\", \"jwt\": \"\${JWT_TOKEN}\"}")
    TOKEN=\$(echo "\$RESPONSE" | jq -r '.auth.client_token')
else
    # File mode (development)
    if [[ -f "/etc/ashchan/openbao/token" ]]; then
        TOKEN=\$(cat /etc/ashchan/openbao/token)
    else
        echo "ERROR: No OpenBao token found" >&2
        exit 1
    fi
fi

# Fetch service-specific secrets
SECRETS=\$(curl -sf "\${OPENBAO_ADDR}/v1/\${SECRET_PATH}" \\
    -H "X-Vault-Token: \${TOKEN}" \\
    --cacert "\${CA_CERT}" \\
    --cert "\${CLIENT_CERT}" \\
    --key "\${CLIENT_KEY}")

if [[ -z "\$SECRETS" ]]; then
    echo "ERROR: Failed to fetch secrets for ${service_short}" >&2
    exit 1
fi

# Fetch global secrets
GLOBAL_SECRETS=\$(curl -sf "\${OPENBAO_ADDR}/v1/\${GLOBAL_SECRET_PATH}" \\
    -H "X-Vault-Token: \${TOKEN}" \\
    --cacert "\${CA_CERT}" \\
    --cert "\${CLIENT_CERT}" \\
    --key "\${CLIENT_KEY}")

# Export secrets as environment variables
# Format: KEY=value
echo "\$SECRETS" | jq -r '.data.data | to_entries[] | "\(.key)=\(.value)"'
echo "\$GLOBAL_SECRETS" | jq -r '.data.data | to_entries[] | "\(.key)=\(.value)"'

# Export database credentials if needed
DB_CREDS=\$(curl -sf "\${OPENBAO_ADDR}/v1/database/ashchan/creds/ashchan" \\
    -H "X-Vault-Token: \${TOKEN}" \\
    --cacert "\${CA_CERT}" \\
    --cert "\${CLIENT_CERT}" \\
    --key "\${CLIENT_KEY}" | jq -r '.data | "DB_USERNAME=\(.username)\nDB_PASSWORD=\(.password)"')

echo "\$DB_CREDS"
EOF

    chmod +x "$fetch_script"

    log_success "Created fetch script: $fetch_script"
}

# Create systemd override for a service
create_systemd_override() {
    local service_short="$1"
    local port="$2"

    local override_dir="/etc/systemd/system/ashchan-${service_short}.service.d"
    local override_file="$override_dir/openbao.conf"

    mkdir -p "$override_dir"

    cat > "$override_file" << EOF
[Service]
# OpenBao Integration
# Fetch secrets before starting the service

# Environment script that fetches secrets
EnvironmentFile=-/run/ashchan/${service_short}.env

# ExecStartPre fetches secrets from OpenBao
ExecStartPre=/usr/local/bin/ashchan-${service_short}-fetch-secrets > /run/ashchan/${service_short}.env

# Ensure directory exists for fetched secrets
ExecStartPre=/bin/mkdir -p /run/ashchan

# Add OpenBao client cert to service environment
Environment="OPENBAO_ADDR=${OPENBAO_ADDR}"
Environment="OPENBAO_CLIENT_CERT=/etc/ashchan/openbao/client/client.crt"
Environment="OPENBAO_CLIENT_KEY=/etc/ashchan/openbao/client/client.key"
Environment="OPENBAO_CA_CERT=/etc/ashchan/openbao/ca.crt"
EOF

    log_success "Created systemd override: $override_file"
}

# Backup original service file
backup_original_service() {
    local service_short="$1"
    local service_file="/etc/systemd/system/ashchan-${service_short}.service"

    if [[ -f "$service_file" ]]; then
        local backup_file="${service_file}.openbao-backup"
        if [[ ! -f "$backup_file" ]]; then
            cp "$service_file" "$backup_file"
            log_info "Backed up original: $backup_file"
        fi
    fi
}

print_header "Updating Ashchan Services for OpenBao"

echo "This script will update all Ashchan services to fetch secrets"
echo "from OpenBao at startup instead of reading .env files."
echo ""
echo "Services to update:"
for service_entry in "${SERVICES[@]}"; do
    IFS=':' read -r name short port <<< "$service_entry"
    echo "  - $name (port $port)"
done
echo ""

read -p "Continue? [Y/n]: " confirm
if [[ "$confirm" =~ ^[Nn]$ ]]; then
    log_info "Update cancelled"
    exit 0
fi

# Create runtime directory
mkdir -p /run/ashchan
chmod 755 /run/ashchan

# Update each service
for service_entry in "${SERVICES[@]}"; do
    IFS=':' read -r name short port <<< "$service_entry"

    print_step "Configuring: $name"

    create_fetch_script "$name" "$short"
    backup_original_service "$short"
    create_systemd_override "$short" "$port"
done

print_header "Service Update Complete"

echo "All services have been configured to use OpenBao."
echo ""
echo "Next steps:"
echo ""
echo "  1. Reload systemd configuration"
echo "     sudo systemctl daemon-reload"
echo ""
echo "  2. Restart all services"
echo "     make restart"
echo ""
echo "  3. Verify services are running"
echo "     make status"
echo ""
echo "  4. Check audit logs for secret access"
echo "     make openbao-audit"
echo ""
echo "Rollback:"
echo "  To revert to .env files, remove the override:"
echo "  sudo rm -rf /etc/systemd/system/ashchan-*.service.d/"
echo "  sudo systemctl daemon-reload"
echo ""

log_success "Update complete!"
